spring:
    application:
        name: jobpoint
    profiles:
        active: dev
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
        encoding: UTF-8
    web:
        resources:
            static-locations: classpath:/static/
            add-mappings: true
    jwt:
        private-key-path: classpath:certs/app.key
        public-key-path: classpath:certs/app.pub
        issuer: jobpoint-api
        expiration-seconds: 86400 # 24 horas