spring:
    application:
        name: jobpoint
    profiles:
        active: dev
    thymeleaf:
        cache: false
    jwt:
        private-key-path: classpath:certs/app.key
        public-key-path: classpath:certs/app.pub
        issuer: jobpoint-api
        expiration-seconds: 86400 # 24 horas

jobpoint:
    admin:
        email: admin@jobpoint.com
        password: admin
        firstName: Admin
        lastName: User